apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: kaptein-api
  namespace: klage
  labels:
    team: klage
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "86400"
spec:
  image: {{ image }}
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  azure:
    application:
      enabled: true
      tenant: {{tenant}}
      claims:
        groups:
        {{#each adRoles}}
          - id: {{value}}
        {{/each}}
        extra:
          - NAVident
  kafka:
    pool: {{kafka_pool}}
  port: 8080
  startup:
    failureThreshold: 20
    initialDelay: {{initialDelay}}
    path: /internal/health
    periodSeconds: 10
    timeout: 4
  liveness:
    path: /internal/health
    initialDelay: {{initialDelay}}
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /internal/isready
    initialDelay: {{isReadyDelay}}
    timeout: 2
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 1Gi
  ingresses:
  {{#each ingresses as |ingress|}}
    - {{ingress}}
  {{/each}}
  replicas:
    min: {{replicasMin}}
    max: {{replicasMax}}
    cpuThresholdPercentage: 80
  accessPolicy:
    inbound:
      rules:
      {{#each inboundApplications as |inbound|}}
        - application: {{inbound.application}}
#        {{#if inbound.namespace}}
          namespace: {{inbound.namespace}}
#        {{/if}}
#        {{#if inbound.cluster}}
          cluster: {{inbound.cluster}}
#        {{/if}}
      {{/each}}
    outbound:
      rules:
        - application: kabal-api
        - application: logging
          namespace: nais-system
      external:
      {{#each externalHosts}}
        - host: {{host}}
      {{/each}}
  env:
  {{#each envs}}
    - name: {{name}}
      value: {{value}}
  {{/each}}
  {{#each adRoles}}
    - name: {{name}}
      value: {{value}}
  {{/each}}
